const AllJokesData = [
    {"id": 1, "joke": "Why don't scientists trust atoms? Because they make up everything!"},
    {"id": 2, "joke": "Why did the scarecrow win an award? Because he was outstanding in his field!"},
    {"id": 3, "joke": "Why don’t skeletons fight each other? They don’t have the guts."},
    {"id": 4, "joke": "What do you call fake spaghetti? An impasta!"},
    {"id": 5, "joke": "What do you get if you cross a snowman and a vampire? Frostbite."},
    {"id": 6, "joke": "Why did the math book look sad? Because it had too many problems."},
    {"id": 7, "joke": "Why don’t some couples go to the gym? Because some relationships don’t work out."},
    {"id": 8, "joke": "I would avoid the sushi if I was you. It’s a little fishy."},
    {"id": 9, "joke": "Want to hear a joke about construction? I’m still working on it."},
    {"id": 10, "joke": "Why don’t programmers like nature? It has too many bugs."},
    {"id": 11, "joke": "Why do cows have hooves instead of feet? Because they lactose."},
    {"id": 12, "joke": "Why can’t you give Elsa a balloon? Because she will let it go."},
    {"id": 13, "joke": "What do you get when you cross a snowman with a dog? Frostbite."},
    {"id": 14, "joke": "Why don’t oysters donate to charity? Because they are shellfish."},
    {"id": 15, "joke": "What do you call cheese that isn't yours? Nacho cheese."},
    {"id": 16, "joke": "How does a penguin build its house? Igloos it together."},
    {"id": 17, "joke": "What time did the man go to the dentist? Tooth hurt-y."},
    {"id": 18, "joke": "Why did the bicycle fall over? Because it was two-tired."},
    {"id": 19, "joke": "Why did the golfer bring two pairs of pants? In case he got a hole in one."},
    {"id": 20, "joke": "Why don’t you ever see elephants hiding in trees? Because they’re so good at it."},
    {"id": 21, "joke": "What do you call a factory that makes good products? A satisfactory."},
    {"id": 22, "joke": "Why was the math book depressed? It had too many problems."},
    {"id": 23, "joke": "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field."},
    {"id": 24, "joke": "What do you call a dinosaur with an extensive vocabulary? A thesaurus."},
    {"id": 25, "joke": "How does a rabbi make coffee? Hebrews it."},
    {"id": 26, "joke": "Why don’t you ever see Santa in a hospital? Because he has private elf care."},
    {"id": 27, "joke": "Why did the tomato turn red? Because it saw the salad dressing!"},
    {"id": 28, "joke": "How do you make a tissue dance? Put a little boogie in it."},
    {"id": 29, "joke": "Why don’t some couples go to the gym? Because some relationships don’t work out."},
    {"id": 30, "joke": "Why did the golfer bring two pairs of pants? In case he got a hole in one."},
    {"id": 31, "joke": "Why was the big cat disqualified from the race? Because it was a cheetah."},
    {"id": 32, "joke": "What do you call a boomerang that doesn’t come back? A stick."},
    {"id": 33, "joke": "Why did the chicken join a band? Because it had the drumsticks."},
    {"id": 34, "joke": "How does NASA organize a party? They planet."},
    {"id": 35, "joke": "What do you call fake spaghetti? An impasta."},
    {"id": 36, "joke": "What do you call a bear with no teeth? A gummy bear."},
    {"id": 37, "joke": "Why can’t you hear a pterodactyl in the bathroom? Because it has a silent pee."},
    {"id": 38, "joke": "Why did the scarecrow win an award? Because he was outstanding in his field!"},
    {"id": 39, "joke": "Why don’t scientists trust atoms? Because they make up everything."},
    {"id": 40, "joke": "What do you call a can opener that doesn’t work? A can’t opener."},
    {"id": 41, "joke": "Why did the bicycle fall over? Because it was two tired."},
    {"id": 42, "joke": "What do you get when you cross a snowman and a vampire? Frostbite."},
    {"id": 43, "joke": "Why don’t skeletons fight each other? They don’t have the guts."},
    {"id": 44, "joke": "What do you call fake spaghetti? An impasta."},
    {"id": 45, "joke": "Why don’t some couples go to the gym? Because some relationships don’t work out."},
    {"id": 46, "joke": "Want to hear a joke about construction? I’m still working on it."},
    {"id": 47, "joke": "Why don’t programmers like nature? It has too many bugs."},
    {"id": 48, "joke": "Why do cows have hooves instead of feet? Because they lactose."},
    {"id": 49, "joke": "Why can’t you give Elsa a balloon? Because she will let it go."},
    {"id": 50, "joke": "What do you get when you cross a snowman with a dog? Frostbite."},
    {"id": 51, "joke": "Why don’t oysters donate to charity? Because they are shellfish."},
    {"id": 52, "joke": "What do you call cheese that isn't yours? Nacho cheese."},
    {"id": 53, "joke": "How does a penguin build its house? Igloos it together."},
    {"id": 54, "joke": "What time did the man go to the dentist? Tooth hurt-y."},
    {"id": 55, "joke": "Why did the bicycle fall over? Because it was two-tired."},
    {"id": 56, "joke": "Why did the golfer bring two pairs of pants? In case he got a hole in one."},
    {"id": 57, "joke": "Why don’t you ever see elephants hiding in trees? Because they’re so good at it."},
    {"id": 58, "joke": "What do you call a factory that makes good products? A satisfactory."},
    {"id": 59, "joke": "Why was the math book depressed? It had too many problems."},
    {"id": 60, "joke": "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field."},
    {"id": 61, "joke": "What do you call a dinosaur with an extensive vocabulary? A thesaurus."},
    {"id": 62, "joke": "How does a rabbi make coffee? Hebrews it."},
    {"id": 63, "joke": "Why don’t you ever see Santa in a hospital? Because he has private elf care."},
    {"id": 64, "joke": "Why did the tomato turn red? Because it saw the salad dressing!"},
    {"id": 65, "joke": "How do you make a tissue dance? Put a little boogie in it."},
    {"id": 66, "joke": "Why don’t some couples go to the gym? Because some relationships don’t work out."},
    {"id": 67, "joke": "Why did the golfer bring two pairs of pants? In case he got a hole in one."},
    {"id": 68, "joke": "Why was the big cat disqualified from the race? Because it was a cheetah."},
    {"id": 69, "joke": "What do you call a boomerang that doesn’t come back? A stick."},
    {"id": 70, "joke": "Why did the chicken join a band? Because it had the drumsticks."},
    {"id": 71, "joke": "How does NASA organize a party? They planet."},
    {"id": 72, "joke": "What do you call fake spaghetti? An impasta."},
    {"id": 73, "joke": "What do you call a bear with no teeth? A gummy bear."},
    {"id": 74, "joke": "Why can’t you hear a pterodactyl in the bathroom? Because it has a silent pee."},
    {"id": 75, "joke": "Why did the scarecrow win an award? Because he was outstanding in his field!"},
    {"id": 76, "joke": "Why don’t scientists trust atoms? Because they make up everything."},
    {"id": 77, "joke": "What do you call a can opener that doesn’t work? A can’t opener."},
    {"id": 78, "joke": "Why did the bicycle fall over? Because it was two tired."},
    {"id": 79, "joke": "What do you get when you cross a snowman and a vampire? Frostbite."},
    {"id": 80, "joke": "Why don’t skeletons fight each other? They don’t have the guts."},
    {"id": 81, "joke": "What do you call fake spaghetti? An impasta."},
    {"id": 82, "joke": "Why don’t some couples go to the gym? Because some relationships don’t work out."},
    {"id": 83, "joke": "Want to hear a joke about construction? I’m still working on it."},
    {"id": 84, "joke": "Why don’t programmers like nature? It has too many bugs."},
    {"id": 85, "joke": "Why do cows have hooves instead of feet? Because they lactose."},
    {"id": 86, "joke": "Why can’t you give Elsa a balloon? Because she will let it go."},
    {"id": 87, "joke": "What do you get when you cross a snowman with a dog? Frostbite."},
    {"id": 88, "joke": "Why don’t oysters donate to charity? Because they are shellfish."},
    {"id": 89, "joke": "What do you call cheese that isn't yours? Nacho cheese."},
    {"id": 90, "joke": "How does a penguin build its house? Igloos it together."},
    {"id": 91, "joke": "What time did the man go to the dentist? Tooth hurt-y."},
    {"id": 92, "joke": "Why did the bicycle fall over? Because it was two-tired."},
    {"id": 93, "joke": "Why did the golfer bring two pairs of pants? In case he got a hole in one."},
    {"id": 94, "joke": "Why don’t you ever see elephants hiding in trees? Because they’re so good at it."},
    {"id": 95, "joke": "What do you call a factory that makes good products? A satisfactory."},
    {"id": 96, "joke": "Why was the math book depressed? It had too many problems."},
    {"id": 97, "joke": "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field."},
    {"id": 98, "joke": "What do you call a dinosaur with an extensive vocabulary? A thesaurus."},
    {"id": 99, "joke": "How does a rabbi make coffee? Hebrews it."},
    {"id": 100, "joke": "Why don’t you ever see Santa in a hospital? Because he has private elf care."}
]


module.exports = AllJokesData;